### ISSUE TITLE
Poly-Kinded Type Families

### ISSUE THREAD

**Issue by jqyu** [target/row-types#19]
I noticed that many of the type families for `Data.Row.Internal` only operate on rows of kind `Row *`, but it seems like it would be just as useful to use these type families (in particular, `(.==)` and `(.+)`) for rows of any kind, since row types can be used for more than just records and variants.

I have a working version here:
https://github.com/jqyu/graphql-row-types/blob/master/src/Data/Row/Poly.hs
and I would be happy to make a PR if you think this is the right approach (:

**Comment by shlevy** [comment]
:+1: on the idea, haven't reviewed the code.

**Comment by dwincort** [comment]
I've thought about this idea before, but only ever in the context of records and variants.  That is, having the ability to have rows of any kind is theoretically interesting, but I hadn't come up with a way to make it useful.  I'm curious what your use for it is.

I think your approach looks fine (basically swapping out `*` for `k` or `Type` where appropriate), and I'd be happy to review a PR if you submit one.  I like that it looks like it will be entirely backwards compatible.

Thanks!

**Comment by jqyu** [comment]
Will do!

If you're wondering the use case I'm playing around with (and I'm not totally sure if this works yet) is using row-types to express a GraphQL schema:
https://github.com/jqyu/graphql-row-types/blob/master/example/GraphQLExample.hs#L53-L293

If my idea makes sense, row types enable us to check certain assertions in the type checker, e.g. if `'Object _ '["Interface"] fields` implements `'Interface _ fields'`, then we must have that `fields` is a subtype of `fields'`. From there, using type families we should be able to describe the implementation for a type definition. In this case, having poly kinded rows to say `schema :: Row TypeDefinition` is slightly nicer than saying something like `schema :: Row *` and relying on the type family implementations to exclude the possibility of rows of unsupported types.

Another more general use case of poly-kinded row types is the ability to express a variant/record functor. This technique is used in PureScript to do things like having an open row of effects, such as in:
https://github.com/natefaubion/purescript-run
