### ISSUE TITLE
Can we add something to allow `HasType` for `Map`ed row?

### ISSUE THREAD

**Issue by yanok** [target/row-types#24]
In particular it'd be nice to be able to derive `Map f r .! l ~ f t` from `r .! l ~ t`, where `r` is polymorphic. It seems like there is no easy way to achieve this now, or am I missing something?

**Comment by dwincort** [comment]
I really wish we could, but I'm not sure how to do it.

**Comment by yanok** [comment]
I end up adding
```
mapHas :: forall f r l t. (r .! l ≈ t) :- (Map f r .! l ≈ f t)
mapHas = Sub $ unsafeCoerce $ Dict @(r .! l ≈ t)
```
to my project. I theorem holds trivially and `~` has no computational content, so `unsafeCoerce` is safe here. I wish we could prove it without `unsafeCoerce` but I don't know how to do this in Haskell...
