### ISSUE TITLE
Design help with default values

### ISSUE THREAD

**Issue by k-bx** [target/row-types#42]
I'd like to request help for designing a solution I'm building for integration test factories together with row-types.

Here's a self-containing repo which can be built/launched via `stack run` https://github.com/k-bx/row-types-default/blob/e6a2b5c03d419038d3fb5301251c2aca71f72d63/src/Main.hs

The two problems I'm trying to solve now:

First, how do I make ability to make parameters implicit with default value to be `Nothing`? Instead of calling `buildProduct (#name .== Nothing .+ #companyId .== Nothing)` I'd like to only be required to mention those parameters which are non-Nothing (which I want to over-write from default).

Second, what would be a good way to pass parameters of `buildCompany` to `buildProduct` under a name `#company`? E.g., I'd like my API to look like this at the end:

```haskell
main = do
  product' <- buildProduct (def (#company .== def (#name .== "My Company")))
  ...
```

and this would build everything with default values, except for product's company name to be `"My Company"`.

Hope this sounds clear. Thanks!

**Comment by k-bx** [comment]
p.s.: I was able to get *some* "default values" functionality via the `vinyl` library in my project, but it has other downsides and I haven't yet explored how would doing inner `"company"` params feel like

**Comment by dwincort** [comment]
Huh, interesting problem.  First thought: would it help if I added a function that allows you to do record overwriting?  Consider:
```haskell
-- | Record overwrite.
--
-- The operation @r .// r'@ creates a new record such that:
--
-- - Any label that is in both @r@ and @r'@ is in the resulting record with the
--   type and value given by the fields in @r@,
--
-- - Any label that is only found in @r@ is in the resulting record.
--
-- - Any label that is only found in @r'@ is in the resulting record.
--
-- This can be thought of as @r@ "overwriting" @r'@.
(.//) :: Rec r -> Rec r' -> Rec (r .// r')
```

Using this, I think I can answer your questions specifically.  You could define a default value for your product to be something like:
```haskell
type ProductRowType = "name" .== String .+ "companyId" .== CompanyId
defProduct :: Rec (Map Maybe ProductRowType)
defProduct = #name .== Nothing .+ #companyId .== Nothing
```
You could make an actual `Default` instance if you like (or use a newtype wrapper if you like that better), but for clarity, I'll leave it like this for now.

Your input value would have type `Subset r ProductRowType => Rec r`, and then you could use Record.map' and the record overwrite function above to get your input to `buildProduct`:
```haskell
buildProduct :: Rec (Map Maybe ProductRowType) -> IO Product

main = do
  product' <- buildProduct ((Record.map' Just $ #name .== "My Company") .// defProduct)
```
(Or you can write `buildProduct (#name .== Just "My Company" .// defProduct)` if you don't mind writing `Just` for each of the fields.)

And, if your product depends on a company that needs to be built, you should be able to nest this just fine with another record.

As a final note, you might want to check out the `toNative` and `fromNative` functions for records.  They let you convert between, say a value of type `Rec ProductRowType` and a value of type `Product` very easily.  Check out [this example](https://target.github.io/row-types/examples/TypeSurgery) for some ideas.

**Comment by k-bx** [comment]
This looks awesome, thank you! I've just tried things you've mentioned and they look great. One thing I wasn't able to implement was the nested row scenario, I will reproduce that on the test repo and post more details later.

**Comment by k-bx** [comment]
Attaching image from an actual code with more fields using this.

Also, I can definitely see how `defPb` could be generated, and even the `BuildPb` type alias could be semi-generated from persistent's model description (but not for the nested stuff probably).

![Screenshot from 2019-05-11 17-09-49](https://user-images.githubusercontent.com/107968/57570896-c92cd200-740f-11e9-9dcd-af1408ccc1ee.png)

**Comment by k-bx** [comment]
@dwincort would appreciate some help with "nested rows". I've updated the repo to first do the no-nested-rows (and use the appropriate commit from row-types with `.//`), then I've made a commit which tries to add `"company" .== BuildCompany` in the `BuildProduct` type. Here's the error I'm getting:

```haskell
/home/kb/workspace/row-types-default/src/Main.hs:41:71: error:
    • Expected kind ‘Row *’,
        but ‘"company" .== BuildCompany’ has kind ‘Row (Row *)’
    • In the second argument of ‘(.+)’, namely
        ‘"company" .== BuildCompany’
      In the type ‘"name" .== String .+ "companyId" .== CompanyId
                   .+ "company" .== BuildCompany’
      In the type declaration for ‘BuildProduct’
   |
41 | type BuildProduct = "name" .== String .+ "companyId" .== CompanyId .+ "company" .== BuildCompany
   |                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I will dig into row-types actual implementation machinery later, but thought you might know the solution off top of your head maybe. Thank you!

**Comment by dwincort** [comment]
I'm not sure I'll have time to really look into this today, but the error message leads me to believe you want to have written `"company" .== Rec BuildCompany`.

Hmm, if you do that, then when you `Map Maybe` over the row type, you'll get a `Maybe (Rec BuildCompany)`, but what you really want is a `Maybe (Rec (Map Maybe BuildCompany))`, right?  I guess there's a bit of a subtlety in nesting these things that I haven't thought through.  I'll think about it and get back to you soon.

**Comment by k-bx** [comment]
Thank you! Definitely no rush with this, current state of things is already "good enough" to get going.

**Comment by dwincort** [comment]
Try changing lines 41-52 to:
```haskell
type BuildProduct = "name" .== String .+ "companyId" .== CompanyId .+ "company" .== Rec (Row.Map Maybe BuildCompany)

defProduct :: Rec (Row.Map Maybe BuildProduct)
defProduct = #name .== Nothing .+ #companyId .== Nothing .+ #company .== Just defCompany

buildProduct ::
  Rec (Row.Map Maybe BuildProduct) -> IO Product
buildProduct ps = do
  productName <- fromParams (ps .! #name) buildName
  let buildThisCompany = buildCompany $ maybe defCompany id (ps .! #company)
  productCompanyId <- fromParamsIns (ps .! #companyId) buildThisCompany
  pure $ Product {..}
```

The issue here is that the `company` element in `BuildProduct` must be a _record_ of `BuildProduct` to make the types work out.  This becomes clear when you think about the value you're going to provide in the definition of `defProduct` -- you currently have `"company" .== BuildCompany`, but this doesn't make sense at  the value  level  because `BuildCompany` isn't  a value.

In my above suggestion, there's an unfortunate redundancy, which is that `defCompany` is used twice: once in the definition of `defProduct` but then once again in the `maybe` call in  `buildProduct`.  This is because the `company` element of `BuildProduct` should _really_ just always be there, but we're making it optional when we write `Rec (Row.Map Maybe BuildProduct)` in the type signature of `buildProduct`.  I know I  suggested using `Row.Map`, but since you never have  a type like `Rec BuildProduct` anyway, it might be better to inline the map.  Then, you could force the `company` element to _not_ be `Maybe`, like so:
```haskell
type BuildCompany = "name" .== Maybe String

defCompany :: Rec BuildCompany
defCompany = #name .== Nothing

buildCompany :: Rec BuildCompany -> IO Company
buildCompany ps = do
  companyName <- fromParams (ps .! #name) buildName
  pure $ Company {..}

type BuildProduct = "name" .== Maybe String .+ "companyId" .== Maybe CompanyId .+ "company" .== Rec BuildCompany

defProduct :: Rec BuildProduct
defProduct = #name .== Nothing .+ #companyId .== Nothing .+ #company .== defCompany

buildProduct ::
  Rec BuildProduct -> IO Product
buildProduct ps = do
  productName <- fromParams (ps .! #name) buildName
  productCompanyId <- fromParamsIns (ps .! #companyId) (buildCompany (ps .! #company))
  pure $ Product {..}
``` 

Now, you  can make fancy nested calls like:
```haskell
buildProduct ((#name .== Just "awesome product" .+ #company .== ((#name .== Just "awesome company") .// defCompany)) .// defProduct)
```
(There's probably a nice way to split  this up onto multiple lines, but I'm not sure what it is :P.)

**Comment by k-bx** [comment]
@dwincort this is awesome, thank you! I especially like the last approach, as it seems more obvious for the end-user/reader who's not familiar with row-types. Closing the issue, feel free to point the repo as docs (or take the example from it).
