### ISSUE TITLE
Feature request: unions aka corecords

### ISSUE THREAD

**Issue by Pitometsu** [target/row-types#55]
Would it make sense to have not-tagged sums ([like](https://hackage.haskell.org/package/union)).
Also pls consider to use `.*` instead of `.+` (in way like Caml using `*` in types) for records, and keep `.+` for variants/unions.

**Comment by dwincort** [comment]
I appreciate the suggestion, but I feel I must decline on both counts.

Untagged sums are a neat idea, but they wouldn't use the core types that are the focus of this library.  They wouldn't use the `Row` kind at all, instead needing something without tags, which means they'd really be a totally different thing from what I've built here.  I'm interested though: would you want to intermix untagged sums with the `Rec`s and `Var`s from this library?  If so, how would you envision that working?  What kinds of functions would there be?

As far as `.+` vs `.*`, I'm not sure your proposal quite makes sense.  First off, keep in mind that there is a `.+` _type operator_ and also a `.+` _function_.  The type operator works just as well for `Rec`s as for `Var`s, or any other type built on top of a row-type that you can think of.  It wouldn't make sense to have `.*` for `Rec`s and `.+` for `Var`s unless you want me to define, essentially, `(.*) = (.+)` (which, if you want to do for your use cases, feel free).  On the other hand, maybe you're asking me to rename the `.+` _function_ to `.*`.  I suppose we _could_ do this, but I like the parallel form we see when the value and type level use the same operator.  Furthermore, there is no `.+` or `.*` operator for `Var`s -- I'm not sure what the meaning would be of "unioning" two `Var`s.

**Comment by Pitometsu** [comment]
> If so, how would you envision that working?

Not sure yet, just assumed that tagged and not-tagged sums and products in one place with common types (or data families) could be handy (e.g. map native ADT to variants of records in case of named fields, or variants of HLists for ADS with anonymous fields, and tuples to union of HLists, however there's no native type for not-tagged sum of tagged records afaik).

> As far as .+ vs .*, I'm not sure your proposal quite makes sense.

Ok, got. Just thinked about `a * b` type in OCaml or `a & b` in new Scala, but, maybe, it more related to Rec then to Row.

**Comment by dwincort** [comment]
> just assumed that tagged and not-tagged sums and products in one place with common types could be handy

This is actually a really good point and something that I ran into: it's really frustrating that, e.g., a value of type `Either Int String` can't be freely converted to a `Var`.  But yeah, I don't see a good way to make this work right now.  It's an interesting problem though, and I'll think about it.

> maybe, it more related to Rec then to Row

Exactly.  There is a decent argument to be made that all uses (both type operator and function) of `.+` really should have been `.*` in the first place, but I think it's a bit late for that, at least for this library.
