### ISSUE TITLE
AllUniqueLabels (V.Map (Either String) r)

### ISSUE THREAD

**Issue by nomeata** [target/row-types#66]
I am running in a problem. I want to write this code:
```
instance CandidRow r => Candid (V.Var r)
instance CandidRow r => CandidVal (V.Var r) where
    asType = VariantT $ fieldOfRow @r

    toCandidVal' v = VariantV (unescapeFieldName t) val
      where (t, val) = V.eraseWithLabels @Candid toCandidVal v

    fromCandidVal' (VariantV f v) = do
        needle <-
            V.fromLabels @Candid $ \l -> do
                guard (f == unescapeFieldName (R.toKey l))
                return $ fromCandidVal v
            <|> Left ("Unexpected variant tag " ++ show (pretty f))
        V.sequence needle
    fromCandidVal' v = Left $ "Unexpected " ++ show (pretty v)
```

The point is that I want `V.fromLabels` to use the `Alternative` instance of `Either String` to pick the right field (based on the `f`). But I want to avoid decoding failures within `fromCandidVal` to cause backtracking here!

So inside `fromLabels` I return the pure `fromCandidVal v`, and only after the right label was found, I want to perform that action. This calls for `V.sequence`, it seems.

But now I get
```
    • Could not deduce: AllUniqueLabels (V.Map (Either String) r)
        arising from a use of ‘V.fromLabels’
      from the context: CandidRow r
```
where
```
type CandidRow r = (Typeable r, AllUniqueLabels r, Forall r Candid)
```

It seems that `AllUniqueLabels r` does not imply `AllUniqueLabels (V.Map f r)`… is there a way to get that?

…

Ah, it seems that there is `fromLabelsMapA` for records, but not for variants. Is there a deep reason for that?

**Comment by nomeata** [comment]
```
fromLabelsMapA :: forall c f g ρ. (Alternative f, Forall ρ c, AllUniqueLabels ρ)
               => (forall l a. (KnownSymbol l, c a) => Label l -> f (g a)) -> f (V.Var (V.Map g ρ))
fromLabelsMapA f = V.fromLabels @(R.IsA c g) @(V.Map g ρ) @f inner
                \\ R.mapForall @g @c @ρ
                \\ R.uniqueMap @g @ρ
   where inner :: forall l a. (KnownSymbol l, R.IsA c g a) => Label l -> f a
         inner l = case R.as @c @g @a of R.As -> f l
```
seems to typecheck and work.

**Comment by dwincort** [comment]
There is no deep reason at all.  For a little while, I was devoting all my attention to `Rec`, and a few nice functions I made never got complementary versions in `Var` -- `fromLabelsMapA` is one of them.  If you'd like to make a PR for this function, I'd be happy to include it, or I can add it myself.

> It seems that `AllUniqueLabels r` does not imply `AllUniqueLabels (V.Map f r)` … is there a way to get that?

It seems you figured out the answer to this one yourself: using `uniqueMap`.  I'm actually really happy that someone other than me was able to navigate the code and figure that out.  Nice! :D

**Comment by nomeata** [comment]
At first I tried to use `\\ uniqeMap` directly, but didn’t get far. Then I grepped for uses of it, and found `fromLabelsMapA`. So I just copied and cargo-culted that, swapping `Applicative` for `Alternative` and other tweaks, until it compiled.

I have that function in my code base now, but wouldn’t mind if I can eventually drop it again, so if you can include it when you do another release, then that’d be appreciated.

**Comment by nomeata** [comment]
Fixed by https://github.com/target/row-types/pull/68 it seems.
