### ISSUE TITLE
Publish row-types-aeson & row-types-barbies

### ISSUE THREAD

**Issue by shinzui** [target/row-types#80]
Can you please publish `row-types-aeson` and `row-types-barbies`?

**Comment by dwincort** [comment]
Oh sure.  Do you know if Cabal v3's public sublibraries are a thing in regular use?  I'd love to just swap the cabal file for row-types with the v3 version (https://github.com/target/row-types/blob/master/row-types.cabal.3), upload to hackage, and have everything work.

**Comment by shinzui** [comment]
> Do you know if Cabal v3's public sublibraries are a thing in regular use?

I'm not sure, unfortunately. I haven't seen them used in other projects.

**Comment by dwincort** [comment]
Well, I looked into cabal v3, but I didn't get anywhere with it.  Instead, here are the libraries you requested:

- https://hackage.haskell.org/package/row-types-aeson-1.0.0.0

- https://hackage.haskell.org/package/row-types-barbies-1.0.0.0

**Comment by shinzui** [comment]
Thank you. I can remove the copy/pasted code from my project now.
