### ISSUE TITLE
See github.com/dwincort/row-types for active maintenance

### ISSUE THREAD

**Issue by dwincort** [target/row-types#84]
To all concerned, this repository is no longer being actively maintained at this site.  The new source of truth for `row-types` can be found at [https://github.com/dwincort/row-types](https://github.com/dwincort/row-types).  Please post issues and submit PRs there from now on.

**Comment by shinzui** [comment]
Does that mean that target is not longer using the library?

**Comment by dwincort** [comment]
I can't comment on that directly as I'm no longer a Target employee.  All I can say is that I am the primary maintainer, I left Target, I had some trouble maintaining the repo while not a Target employee, and so I am now maintaining it off of my personal github account.

**Comment by shinzui** [comment]
Got it. Thank you for replying and for maintaining this great library. I hope Haskell adopts row polymorphism natively in the future. I know there is a [proposal](https://github.com/ghc-proposals/ghc-proposals/pull/180), but it has been dormant for some time.

**Comment by nomeata** [comment]
Maybe update the hackage metadata at https://hackage.haskell.org/package/row-types (or simply make a new release)?

**Comment by dwincort** [comment]
@nomeata Thanks for the tip!  I haven't done much to warrant a new release, so I took your advice of updating the hackage metadata.
