### ISSUE TITLE
Should the aeson instances omit `Nothing` fields?

### ISSUE THREAD

**Issue by michaelpj** [target/row-types#85]
When generating instances, `aeson` can be configured to omit `Nothing` fields. At the moment the instances for `Rec` don't do this: `Nothing` gets serialized as `null` and you can't omit such fields in the JSON. It would be nice to have a way to express records with fields that can be missing.

I don't really know what to do about this: both seem sensible, and in `aeson` this is configurable, and arguably it's a bit weird to treat `Maybe` specially like this, see: https://github.com/haskell/aeson/issues/646

**Comment by dwincort** [comment]
Yeah, this is an awkward problem.  Obviously, if I provide an aeson instance, then I have to choose one or the other,  and my inclination is to use the default aeson instance (that is, the one in this library).  I'm sure it's possible to provide a function like `genericToJSON` that takes some sort of `Options` (e.g., `recToJSON :: (...) => Options -> Rec r -> Value`), but this opens a whole can of worms that I'm not interested in writing right now.  After all, there are a lot more options possible than just `omitNothingFields`.  If you want to write something like that and make a pull request (maybe a second module in `row-types-aeson`?), I'm sure I'd be happy to accept.

I'm sure you've already thought of using newtypes and writing your own instance.  One option is to use `Typeable` as a constraint to identify `Nothing` fields.  (Hmm, how does `aeson` do it?)  Another thing you could try is using `Rec`'s `Generic` instance itself, i.e., converting to the generic representation and then calling `toJSON` (or wrapping the generic representation in a newtype and making aeson instances with appropriate options).

Sorry I can't be more helpful.  Good luck!

**Comment by michaelpj** [comment]
I moved this to your repo btw!

Yes, it's rather complicated. In this instance I'm trying to avoid adding lots of wrappers, so I may just take advantage of the fact that the instance in `row-types-aeson` is an orphan and so I can provide my own implementation.
